### ISSUE TITLE
Out image to show the lines of the tiles (optional parameter of not showing them)

### ISSUE THREAD

**Issue by brito-rafa** [WillBolduc05/imageToPortugueseTile#5]
The image generated by the program should show lines of the tiles (default is on), although an optional parameter to *not* show the tile lines.
Example of the lines below:
<img width="567" alt="image" src="https://github.com/WillBolduc05/imageToPencilSketch/assets/8331576/d4ef3674-071d-4c1e-b467-2f5db13cbccc">

**Comment by WillBolduc05** [comment]
partially resolved, the coloring of the lines is iffy though.

**Comment by brito-rafa** [comment]
Duplicated, let's track on issue #11
